<?php

namespace EntityBundle\Repository;

/**
 * AdministrateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrateurRepository extends \Doctrine\ORM\EntityRepository
{
}
