<?php

namespace EntityBundle\Repository;

/**
 * LocalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationRepository extends \Doctrine\ORM\EntityRepository
{
}
